# Generated by Django 5.0.7 on 2024-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuths', '0004_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('vendor', 'Vendor')], default='buyer', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
