# Generated by Django 5.0.7 on 2024-08-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuths', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
