# Generated by Django 5.0.7 on 2024-08-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuths', '0008_remove_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
