# Generated by Django 5.0.7 on 2024-08-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuths', '0009_remove_user_is_vendor_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], default=None, max_length=20),
        ),
    ]
