# Generated by Django 5.0.7 on 2024-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='chat_response_time',
            field=models.CharField(default='100', max_length=200),
        ),
    ]
