# Generated by Django 5.0.7 on 2024-08-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cartorderitems_options_address_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
