# Generated by Django 5.0.7 on 2024-08-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_address_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='image')),
                ('phone', models.CharField(max_length=30)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
