# Generated by Django 5.0.7 on 2024-08-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
