# Generated by Django 5.0.7 on 2024-08-13 12:36

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cartorder_address_cartorder_city_cartorder_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh1234', blank=True, length=5, max_length=20, null=True, prefix='sku'),
        ),
    ]
