# Generated by Django 5.0.7 on 2024-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
