# Generated by Django 5.0.7 on 2024-08-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_tags_remove_cartorder_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
