# Generated by Django 5.0.7 on 2024-08-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_cartorder_price_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='chat_response_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='days_return',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shipping_on_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='trust_rating',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='warranty_period',
        ),
    ]
