# Generated by Django 5.0.7 on 2024-08-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_vendor_chat_response_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='stripe_payment_intent',
            new_name='paystack_payment_intent',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tracking_website_address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
