# Generated by Django 5.0.7 on 2024-08-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_stripe_payment_intent_vendor_paystack_payment_intent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='revenue',
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='core.vendor'),
            preserve_default=False,
        ),
    ]
