# Generated by Django 5.0.7 on 2024-08-28 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_product_revenue_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
            preserve_default=False,
        ),
    ]
