# Generated by Django 5.0.7 on 2024-08-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_cartorderitems_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='product',
        ),
    ]
